name: Deploy to GitHub Pages

on:
 push:
  branches:
   - main # or your default branch

jobs:
 deploy:
  runs-on: ubuntu-latest

  permissions:
   contents: write

  steps:
   - name: Checkout Repository
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: '22'
      # cache: 'pnpm'

   - name: Install pnpm
     run: |
      npm install -g pnpm
      echo "$(npm config get prefix)/bin" >> $GITHUB_PATH # Add global npm bin to PATH
     shell: bash # Explicitly use bash to ensure shell commands work as expected

   - name: Install dependencies
     run: pnpm install

   - name: Build Project
     run: pnpm run build # or 'vite build'

   - name: Deploy to GitHub pages
     uses: peaceiris/actions-gh-pages@v4
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist